sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build thesis.tex
deploy:
  provider: releases
  api_key:
    secure: C72ftYw3iPpxHH8doRe6pzx7d078pHTkSK7OUaB1gf1I2xUd6bn5P/OEiHZJfTh9HKcUqfnR5XrwVShuYf+BiwSZWGrlLNDzoZMd7EAEps1RAwt61pY9uj6/xnAzmh+nK8OdaWNISewjSPjgsrRBQMvskL5IIdqkALejid7bgP/UKK4SWf3AnT1uRnuYQhXMoomhat4fNSn6N/BeJY1030fxXorXRuLhOMXhxbMYNHO4NQ76cV+3rmxwHV1tKpuw3Zwn+lVICmm12x6P6L5M0bRYM5Y9EanNfS1J9EsMp7kMqdcjbK0HlTnvfRP5LgHgxqcPGSUBtyrE6WEyCTyxkWTUoHzeZymP59dUto95MHa2wOka5ffKOKk0yxLk6i331SYkIgMAI29/NEx97DwmuFtJESUQPWZV47evRrn2q+LvRk2zQ6048uU+B7bZE1//RapAX7pOWcWwjsCniZwMPA5GNX7BAGZhZkdwNkPtKMxo0KPKFKrTeQXNpCWVf/i9nzyAhU3UECuZWLAzyuO5+mJ1/tME/KP3XdmpDTEd9JxR3pWlExHK97vtRbd1otWUEDXOYfvglFamqr45DAxKfld8Trr6SIIT7cwPp7nNKz4A5Dtv0fTF+YH67mSfgWoV8h16ngSfi6yCc1sIvoQ6LqBNv2l1BYGG+R3fFHjr+/o=
  file:
  - _build/thesis.pdf
  skip_cleanup: true
  on:
    tags: true
